namespace PoCiSys.Gateway;

public static class ChatPage
{
    public const string Html = """
<!doctype html><!-- A reference client for the model; the evidence remains independent. -->
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>PoCiSys Chat</title><style>
:root{color-scheme:dark;--bg:#0d1417;--panel:#162126;--panel2:#1c2a30;--line:#294149;--cyan:#54d9e5;--text:#eef7f8;--muted:#93a8b0;--bad:#ff8279}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 20% 0,#17323a 0,var(--bg) 42%);color:var(--text);font:14px Inter,Segoe UI,sans-serif;height:100vh;overflow:hidden}
.shell{height:100vh;display:grid;grid-template-columns:270px 1fr}.side{border-right:1px solid var(--line);background:#111b1f;padding:20px;display:flex;flex-direction:column;gap:18px}.brand{font-size:21px;font-weight:750}.brand span{color:var(--cyan)}
.side a{color:var(--muted);text-decoration:none}.side a:hover{color:var(--cyan)}.field label{display:block;color:var(--muted);font-size:12px;margin-bottom:7px}.field select{width:100%;background:#0d171a;color:var(--text);border:1px solid var(--line);border-radius:9px;padding:10px}.status{border:1px solid var(--line);border-radius:10px;padding:11px;line-height:1.4;color:var(--muted)}.status.ok{color:var(--cyan)}.status.bad{color:var(--bad)}
button{font:inherit}.secondary,.send{border:1px solid var(--line);background:#17272d;color:var(--text);padding:10px 13px;border-radius:9px;cursor:pointer}.secondary:hover,.send:hover{border-color:var(--cyan)}.privacy{margin-top:auto;color:var(--muted);font-size:12px;line-height:1.45}
.main{min-width:0;display:flex;flex-direction:column}.top{height:64px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 24px}.top strong{font-size:15px}.badge{border:1px solid var(--line);border-radius:999px;padding:6px 10px;color:var(--cyan);font-size:11px}
.messages{flex:1;overflow:auto;padding:28px max(24px,calc((100% - 820px)/2));scroll-behavior:smooth}.welcome{border:1px solid var(--line);background:#132026;border-radius:14px;padding:20px;line-height:1.55;color:#c8d6da}.welcome h1{font-size:21px;margin:0 0 8px;color:var(--text)}.message{display:grid;grid-template-columns:36px 1fr;gap:12px;margin:22px 0}.avatar{width:34px;height:34px;border:1px solid var(--line);border-radius:10px;display:grid;place-items:center;color:var(--cyan);font-weight:700}.message.user .avatar{color:#d9e2e4}.who{font-size:12px;color:var(--muted);margin:2px 0 6px}.content{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.6}.typing:after{content:'▍';color:var(--cyan);animation:blink .8s infinite}@keyframes blink{50%{opacity:0}}
.composer{border-top:1px solid var(--line);padding:16px max(24px,calc((100% - 820px)/2)) 20px}.composebox{display:grid;grid-template-columns:1fr auto;gap:10px;background:var(--panel);border:1px solid var(--line);border-radius:13px;padding:9px}.composebox:focus-within{border-color:#3a6871}.composebox textarea{resize:none;max-height:180px;min-height:44px;border:0;outline:0;background:transparent;color:var(--text);padding:11px;font:inherit;line-height:1.4}.send{background:#17353c;border-color:#34717b;align-self:end}.hint{color:var(--muted);font-size:11px;margin:7px 4px 0}
@media(max-width:720px){.shell{display:flex;flex-direction:column}.side{display:grid;grid-template-columns:minmax(0,1fr) auto;border-right:0;border-bottom:1px solid var(--line);padding:10px 15px;gap:8px}.side .brand,.side #refresh,.side #status,.side .privacy{display:none}.side .field label{display:none}.side .field select{height:40px}.side #newChat{height:40px;padding:8px 11px}.side a{grid-column:1/-1;font-size:11px}.main{flex:1;min-height:0}.top{height:54px;padding:0 16px}.messages,.composer{padding-left:15px;padding-right:15px}.messages{padding-top:18px}}
</style></head><body><div class="shell"><aside class="side"><div class="brand">PoCiSys <span>Chat</span></div><div class="field"><label for="model">AI model</label><select id="model"><option value="">Checking connection…</option></select></div><div class="field"><label for="thinking">Thinking (Ollama)</label><select id="thinking"><option value="off" selected>Off - deterministic tests</option><option value="normal">Normal - model reasoning</option></select></div><div class="field"><label for="maxTokens">Maximum output tokens</label><select id="maxTokens"><option value="64">64</option><option value="128">128</option><option value="256" selected>256</option><option value="512">512</option><option value="1024">1024</option></select></div><button id="refresh" class="secondary">Refresh models</button><button id="newChat" class="secondary">New conversation</button><div id="status" class="status">Connecting to the configured AI…</div><a href="/admin">Open administrator dashboard →</a><div class="privacy">This reference chat keeps the conversation only in this browser tab. PoCiSys Gateway forwards it to the configured AI but does not save the text.</div></aside>
<main class="main"><header class="top"><strong>Private reference chat</strong><span class="badge">GATEWAY OBSERVED</span></header><section id="messages" class="messages"><div id="welcome" class="welcome"><h1>Talk through PoCiSys</h1><div>This chat verifies the complete path from your browser through the Gateway to the selected AI. Timing, usage and integrity measurements appear in the administrator dashboard.</div></div></section>
<footer class="composer"><form id="form" class="composebox"><textarea id="prompt" rows="1" maxlength="100000" placeholder="Message the selected AI…" aria-label="Message"></textarea><button id="send" class="send" type="submit">Send</button></form><div class="hint">Enter sends · Shift+Enter adds a line · Nothing is saved when this tab closes</div></footer></main></div>
<script>
const model=document.getElementById('model'),thinking=document.getElementById('thinking'),maxTokens=document.getElementById('maxTokens'),statusBox=document.getElementById('status'),messagesBox=document.getElementById('messages'),promptBox=document.getElementById('prompt'),sendButton=document.getElementById('send'),chatForm=document.getElementById('form'),refreshButton=document.getElementById('refresh'),newChatButton=document.getElementById('newChat'),preferenceKey='pocisys-chat-preferences';let provider='ollama',history=[],running=null,sessionId=(crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random());
function restorePreferences(){try{const saved=JSON.parse(localStorage.getItem(preferenceKey)||'{}');if(['off','normal'].includes(saved.thinking))thinking.value=saved.thinking;if(['64','128','256','512','1024'].includes(saved.maxTokens))maxTokens.value=saved.maxTokens}catch{}}function savePreferences(){try{localStorage.setItem(preferenceKey,JSON.stringify({thinking:thinking.value,maxTokens:maxTokens.value}))}catch{}}
function setStatus(text,kind=''){statusBox.textContent=text;statusBox.className='status '+kind}function addMessage(role,text=''){document.getElementById('welcome')?.remove();const row=document.createElement('div');row.className='message '+role;const avatar=document.createElement('div');avatar.className='avatar';avatar.textContent=role==='user'?'YOU':'AI';const wrap=document.createElement('div');const who=document.createElement('div');who.className='who';who.textContent=role==='user'?'You':'Selected AI';const content=document.createElement('div');content.className='content';content.textContent=text;wrap.append(who,content);row.append(avatar,wrap);messagesBox.append(row);messagesBox.scrollTop=messagesBox.scrollHeight;return content}
async function loadModels(){setStatus('Testing the AI connection…');model.innerHTML='<option value="">Checking…</option>';try{const result=await fetch('/pocisys/api/chat/config').then(r=>r.json());if(!result.chatEnabled){model.innerHTML='<option value="">Chat disabled</option>';setStatus('Built-in Chat is disabled in Setup.','bad');return}if(!result.connected){model.innerHTML='<option value="">No models available</option>';setStatus(result.explanation||'The AI could not be reached.','bad');return}provider=result.provider;model.innerHTML='';for(const name of result.models){const option=document.createElement('option');option.value=name;option.textContent=name;model.append(option)}if(result.defaultModel&&result.models.includes(result.defaultModel))model.value=result.defaultModel;setStatus(result.explanation,'ok')}catch{model.innerHTML='<option value="">Connection unavailable</option>';setStatus('PoCiSys could not test the AI connection. Open the administrator dashboard to check the address.','bad')}}
function parseOllama(line,accept){if(!line.trim())return;const item=JSON.parse(line);if(item.error)throw new Error(item.error);accept(item.message?.content??item.response??'')}function parseOpenAi(line,accept){line=line.trim();if(!line.startsWith('data:'))return;const data=line.slice(5).trim();if(data==='[DONE]')return;const item=JSON.parse(data);if(item.error)throw new Error(item.error.message||'AI provider error');accept(item.choices?.[0]?.delta?.content??'')}
async function sendMessage(text){if(!model.value)throw new Error('Choose an available model first.');history.push({role:'user',content:text});addMessage('user',text);const output=addMessage('assistant');output.classList.add('typing');running=new AbortController();sendButton.textContent='Stop';let answer='';try{const path=provider==='ollama'?'/api/chat':'/v1/chat/completions',limit=Number(maxTokens.value);const body=provider==='ollama'?{model:model.value,messages:history,stream:true,think:thinking.value==='normal',options:{num_predict:limit}}:{model:model.value,messages:history,stream:true,max_tokens:limit,stream_options:{include_usage:true}};const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-PoCiSys-Session':sessionId},body:JSON.stringify(body),signal:running.signal});if(!response.ok)throw new Error('AI request failed with HTTP '+response.status+'.');const reader=response.body.getReader(),decoder=new TextDecoder();let pending='';while(true){const part=await reader.read();if(part.done)break;pending+=decoder.decode(part.value,{stream:true});const lines=pending.split('\n');pending=lines.pop();for(const line of lines)(provider==='ollama'?parseOllama:parseOpenAi)(line,delta=>{if(delta){answer+=delta;output.textContent=answer;messagesBox.scrollTop=messagesBox.scrollHeight}})}if(pending.trim())(provider==='ollama'?parseOllama:parseOpenAi)(pending,delta=>{answer+=delta;output.textContent=answer});if(answer)history.push({role:'assistant',content:answer});else output.textContent='The AI completed without returning visible text.'}catch(error){output.textContent=error.name==='AbortError'?'Response stopped.':'Could not complete the request: '+error.message}finally{output.classList.remove('typing');running=null;sendButton.textContent='Send'}}
chatForm.addEventListener('submit',async event=>{event.preventDefault();if(running){running.abort();return}const text=promptBox.value.trim();if(!text)return;promptBox.value='';await sendMessage(text)});promptBox.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();chatForm.requestSubmit()}});promptBox.addEventListener('input',()=>{promptBox.style.height='auto';promptBox.style.height=Math.min(promptBox.scrollHeight,180)+'px'});thinking.addEventListener('change',savePreferences);maxTokens.addEventListener('change',savePreferences);refreshButton.onclick=loadModels;newChatButton.onclick=()=>{if(running)running.abort();history=[];sessionId=(crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random());messagesBox.innerHTML='<div id="welcome" class="welcome"><h1>New conversation</h1><div>The previous conversation has been removed from this browser tab. Start a new message when ready.</div></div>'};restorePreferences();loadModels();
</script></body></html>
""";
}
