namespace PoCiSys.Gateway;

public static class Dashboard
{
    public const string Html = """
<!doctype html><!-- The cat watches the model. The mouse watches the proof. Neither touches the answer. -->
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>PoCiSys Gateway</title><style>
:root{color-scheme:dark;--bg:#101619;--panel:#172126;--line:#294049;--cyan:#53d8e5;--muted:#91a5ad;--text:#edf7f8;--bad:#ff8178;--warn:#ffd479}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 15% 0,#19343b 0,#101619 38%);font:14px Inter,Segoe UI,sans-serif;color:var(--text)}main{max-width:1180px;margin:auto;padding:28px}
header{display:flex;align-items:center;justify-content:space-between;margin-bottom:18px}.brand{font-size:23px;font-weight:750;letter-spacing:.4px}.brand span,.ok{color:var(--cyan)}.pill{border:1px solid var(--line);border-radius:999px;padding:7px 12px;color:var(--cyan);background:#142126}
nav{display:flex;gap:7px;margin-bottom:20px;overflow:auto}.tabbtn{border:1px solid transparent;background:transparent;color:var(--muted);padding:9px 13px;border-radius:9px;cursor:pointer}.tabbtn.active{background:#1a2b31;border-color:var(--line);color:var(--text)}.chatlink{margin-left:auto;border:1px solid var(--line);color:var(--cyan);padding:9px 13px;border-radius:9px;text-decoration:none;white-space:nowrap}
.tab{display:none}.tab.active{display:block}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:13px;margin-bottom:18px}.card,.panel{background:rgba(23,33,38,.94);border:1px solid var(--line);border-radius:14px}.card{padding:17px}.label{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.8px}.value{font-size:25px;margin-top:8px;font-weight:700}
.panel{overflow:hidden;margin-bottom:15px}.panel h2{font-size:15px;margin:0;padding:17px;border-bottom:1px solid var(--line)}.copy{padding:17px;line-height:1.55;color:#c9d7db}.grid{display:grid;grid-template-columns:1fr 1fr;gap:13px}.setting{padding:15px;border-bottom:1px solid #22333a}.setting:last-child{border-bottom:0}.setting strong{display:block;margin-bottom:5px}.setting p{color:var(--muted);margin:0;line-height:1.45}.setting code{float:right;color:var(--cyan)}
table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:12px 14px;border-bottom:1px solid #22333a;white-space:nowrap}th{font-size:11px;color:var(--muted);text-transform:uppercase}td.route{max-width:260px;overflow:hidden;text-overflow:ellipsis}.bad{color:var(--bad)}.warn{color:var(--warn)}.empty{padding:35px;text-align:center;color:var(--muted)}button.action{border:1px solid var(--cyan);background:#173139;color:var(--text);padding:9px 14px;border-radius:8px;cursor:pointer}pre{white-space:pre-wrap;word-break:break-all;color:#b8c9ce}
td.reason{min-width:280px;max-width:430px;white-space:normal;line-height:1.4;color:#c9d7db}
footer{color:var(--muted);margin-top:15px;font-size:12px}.modal{position:fixed;inset:0;background:#071013e8;display:none;align-items:center;justify-content:center;padding:18px;z-index:10}.modal.open{display:flex}.wizard{width:min(680px,100%);max-height:90vh;overflow:auto;background:var(--panel);border:1px solid var(--line);border-radius:16px;box-shadow:0 25px 80px #0009}.wizardPage{display:none;padding:26px}.wizardPage.active{display:block}.wizard h1{font-size:23px;margin:0 0 10px}.wizard p,.wizard li{color:#b9c9ce;line-height:1.55}.choice{display:block;border:1px solid var(--line);border-radius:10px;padding:13px;margin:9px 0;background:#132025}.choice input{margin-right:9px}.field{margin:14px 0}.field label{display:block;margin-bottom:6px}.field select,.field input[type=number],.field input[type=url]{width:100%;padding:10px;background:#0f191d;color:var(--text);border:1px solid var(--line);border-radius:8px}.connectionResult{border:1px solid var(--line);border-radius:9px;padding:11px;color:var(--muted);margin-top:10px}.connectionResult.ok{color:var(--cyan)}.connectionResult.bad{color:var(--bad)}.wizardActions{display:flex;justify-content:space-between;padding:16px 26px;border-top:1px solid var(--line)}.secondary{border:1px solid var(--line);background:transparent;color:var(--text);padding:9px 14px;border-radius:8px;cursor:pointer}@media(max-width:800px){.cards,.grid{grid-template-columns:1fr 1fr}.panel{overflow:auto}main{padding:18px}.chatlink{margin-left:0}}@media(max-width:520px){.cards,.grid{grid-template-columns:1fr}}
</style></head><body><main><header><div class="brand">PoCiSys <span>Gateway</span></div><div class="pill">PRIVATE · LOCAL</div></header>
<nav><button class="tabbtn active" data-tab="overview">Overview</button><button class="tabbtn" data-tab="requests">AI requests</button><button class="tabbtn" data-tab="baselines">Model baselines</button><button class="tabbtn" data-tab="settings">Settings explained</button><button class="tabbtn" data-tab="kaspa">Kaspa anchoring</button><a class="chatlink" href="/">Open Chat ↗</a></nav>
<section id="overview" class="tab active"><div class="cards"><div class="card"><div class="label">Completed requests</div><div class="value" id="requestCount">0</div></div><div class="card"><div class="label">Average tokens/second</div><div class="value" id="tps">—</div></div><div class="card"><div class="label">Average total time</div><div class="value" id="latency">—</div></div><div class="card"><div class="label">Needs attention</div><div class="value" id="failures">0</div></div></div>
<div class="grid"><article class="panel"><h2>What this app is doing</h2><div class="copy">Your software sends its AI requests to PoCiSys. PoCiSys immediately forwards them to the AI service and measures the response while it passes back. It does not keep the question or answer. This gives you a neutral record of speed, timing, reported model and failures.</div></article><article class="panel"><h2>How the gauges work</h2><div class="copy"><b>First output</b> is how long the AI takes to begin answering. <b>Tokens/second</b> uses the AI service’s token count when supplied. <b>Total time</b> covers the complete request. Measurements marked unavailable are never guessed.</div></article></div>
<article class="panel"><h2>What PoCiSys can and cannot conclude</h2><div class="copy">PoCiSys can flag unexpected model names, failures, slowdowns and behavior that differs sharply from a learned baseline. Those are auditable warning signs. They do not by themselves prove why an AI behaved differently or that someone acted maliciously.</div></article></section>
<section id="requests" class="tab"><article class="panel"><h2>Recent AI requests</h2><div class="copy">Each row is one exchange. Only measurements and one-way body hashes are shown; prompt and answer text are not retained.</div><div id="requestContent" class="empty">Waiting for AI traffic through the Gateway…</div></article></section>
<section id="baselines" class="tab"><article class="panel"><h2>Learned normal behavior by model</h2><div class="copy">PoCiSys learns separate averages for each reported model. It waits for the number of successful requests chosen in Settings before trusting a baseline. After that, it flags unusually large changes using both normal variation and percentage safeguards, so a single small fluctuation is not treated as a problem.</div><div id="baselineContent" class="empty">No model baseline has started.</div></article></section>
<section id="settings" class="tab"><article class="panel"><h2>Current settings in plain language</h2><div id="settingsContent" class="empty">Loading settings…</div><div class="setting"><button class="action" id="reopenSetup">Change monitoring setup</button><p style="margin-top:9px">Reopens the guided setup without deleting measurements.</p></div></article></section>
<section id="kaspa" class="tab"><article class="panel"><h2>Optional public proof</h2><div class="copy">Kaspa anchoring is optional and is never part of the live AI request. PoCiSys groups private receipt hashes into one Merkle root and later places only that compact commitment in a transaction payload. Prompts, answers and customer identity stay off-chain.</div><div class="setting"><strong>Current mode <code id="kaspaMode">OFF</code></strong><p id="kaspaExplanation">Loading…</p></div><div class="setting"><button class="action" id="simulate">Create safe simulation</button><p style="margin-top:9px">Builds the exact commitment payload shape without opening a wallet, spending KAS or broadcasting.</p><pre id="anchorResult"></pre></div></article></section>
<footer>Live receipts and baselines are bounded in memory and disappear when Gateway restarts. Persistent signed ancestry remains a separate opt-in module.</footer></main>
<div id="setupModal" class="modal"><div class="wizard"><section class="wizardPage" data-step="welcome"><h1>Welcome to PoCiSys</h1><p>This setup chooses what PoCiSys watches and what stays private. You can change every choice later.</p><p>The Gateway sits between your software and its AI service. It measures the exchange without deciding what the AI should say.</p></section>
<section class="wizardPage" data-step="modules"><h1>Choose your modules</h1><p>You will be guided through the selected modules in order.</p><label class="choice"><input id="modChat" type="checkbox" checked><b>Built-in reference chat</b><br>Talk to the AI from a browser for personal use and end-to-end testing.</label><label class="choice"><input id="modBaselines" type="checkbox" checked><b>Model baselines</b><br>Learn normal speed and timing separately for each model.</label><label class="choice"><input id="modMonitor" type="checkbox" checked><b>Passive Monitor companion</b><br>Independently watch the local runtime and hardware without connecting to the model.</label><label class="choice"><input id="modEvidence" type="checkbox"><b>Saved private evidence</b> · next checkpoint<br>Keep signed ancestry after restart. This build leaves it off.</label><label class="choice"><input id="modKaspa" type="checkbox"><b>Kaspa commitment planning</b><br>Prepare optional public commitments. Simulation is safe and spends nothing.</label></section>
<section class="wizardPage" data-step="gateway"><h1>Connect your AI</h1><p>Enter the address where the AI service is listening. PoCiSys will test only its model-list endpoint; it will not send a prompt.</p><div class="field"><label for="backendAddress">AI service address</label><input id="backendAddress" type="url" value="http://127.0.0.1:11434" required></div><div class="field"><label for="backendProvider">Compatibility</label><select id="backendProvider"><option value="auto">Detect automatically</option><option value="ollama">Ollama native</option><option value="openai">OpenAI-compatible</option></select></div><button class="action" id="testConnection" type="button">Save and test connection</button><div id="connectionResult" class="connectionResult">Not tested yet.</div><div class="field"><label for="defaultModel">Default model for built-in Chat</label><select id="defaultModel"><option value="">Test the connection to find models</option></select></div><p>Applications use <b>http://127.0.0.1:8719</b> as their replacement AI address. Provider keys remain separate and are never displayed here.</p></section>
<section class="wizardPage" data-step="chat" data-module="chat"><h1>Built-in reference chat</h1><p>After setup, opening <b>http://127.0.0.1:8719</b> brings up a working chat. It keeps conversation text only in the open browser tab and sends each request through the measured Gateway.</p><p>Use this for personal conversations, fit testing, context testing, and proving the integration works. Companies can instead connect their existing portal to the same Gateway routes.</p></section>
<section class="wizardPage" data-step="baselines" data-module="baselines"><h1>Choose monitoring sensitivity</h1><div class="field"><label for="sensitivity">How quickly should PoCiSys flag a large change?</label><select id="sensitivity"><option value="relaxed">Relaxed — fewer alerts</option><option value="balanced" selected>Balanced — recommended</option><option value="strict">Strict — catches smaller changes</option></select></div><div class="field"><label for="learningCount">Successful requests before a baseline is trusted</label><input id="learningCount" type="number" min="5" max="100" value="5"></div><label class="choice"><input id="trackContext" type="checkbox" checked>Watch context growth, slowdown and sudden context drops</label><p>For conversation-specific context checks, the client may send an <b>X-PoCiSys-Session</b> label. PoCiSys immediately hashes it and never stores the original label.</p></section>
<section class="wizardPage" data-step="monitor" data-module="monitor"><h1>Passive Monitor companion</h1><p>Open PoCiSys Monitor on the same machine as the local AI runtime. It observes process identity, executable changes, model hints, ports and resource behavior without making AI requests.</p><p>Gateway-to-Monitor correlation is the next integration checkpoint. Until then, each module remains useful and independently testable.</p></section>
<section class="wizardPage" data-step="evidence" data-module="evidence"><h1>Saved private evidence</h1><p>This option is intentionally unavailable in the current Gateway checkpoint. Live hashes are temporary. The next release will add signed, bounded disk ancestry with explicit retention and deletion controls.</p></section>
<section class="wizardPage" data-step="kaspa" data-module="kaspa"><h1>Kaspa commitment policy</h1><div class="field"><label for="kaspaModeChoice">Anchoring mode</label><select id="kaspaModeChoice"><option value="off">Off</option><option value="simulation">Simulation — no wallet or broadcast</option></select></div><div class="grid"><div class="field"><label for="anchorEvents">Anchor after this many events</label><input id="anchorEvents" type="number" min="10" max="100000" value="1000"></div><div class="field"><label for="anchorMinutes">Or after this many minutes</label><input id="anchorMinutes" type="number" min="1" max="1440" value="5"></div></div><p>Whichever limit is reached first closes the batch. Real testnet/mainnet signing stays disabled until the isolated official wallet worker is installed and explicitly enabled.</p></section>
<section class="wizardPage" data-step="finish"><h1>Ready to observe</h1><p>Open <b>http://127.0.0.1:8719</b> to chat, or point another application at that Gateway address. The administrator dashboard will explain what PoCiSys sees.</p><p>Nothing is sent to Kaspa unless an administrator later enables a real signer. Nothing in this setup uploads prompts or answers anywhere except the AI service you selected.</p></section><div class="wizardActions"><button class="secondary" id="wizardBack">Back</button><button class="action" id="wizardNext">Next</button></div></div></div>
<script>
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));const num=(v,s='')=>v==null?'—':Number(v).toFixed(1)+s;
document.querySelectorAll('.tabbtn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabbtn,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active')});
function badge(v){return v==='needs_attention'?'<span class="bad">Needs attention</span>':v==='within_baseline'?'<span class="ok">Within baseline</span>':'<span class="warn">Learning</span>'}
const reason=v=>esc((v||[]).join(' ')||'No anomaly detected.');
async function refresh(){try{const [sr,rr,br]=await Promise.all([fetch('/pocisys/api/summary'),fetch('/pocisys/api/receipts?limit=50'),fetch('/pocisys/api/baselines')]);const s=await sr.json(),r=await rr.json(),bs=await br.json();requestCount.textContent=s.completedRequests;tps.textContent=num(s.averageTokensPerSecond);latency.textContent=num(s.averageLatencyMs,' ms');failures.textContent=r.filter(x=>x.assessment==='needs_attention').length;if(r.length)requestContent.className='',requestContent.innerHTML='<table><thead><tr><th>Time</th><th>Route</th><th>Model</th><th>Assessment</th><th>Why</th><th>Status</th><th>First output</th><th>Tk/s</th><th>Tokens</th></tr></thead><tbody>'+r.map(x=>`<tr><td>${new Date(x.started_at).toLocaleTimeString()}</td><td class="route">${esc(x.route)}</td><td>${esc(x.model||'Unreported')}</td><td>${badge(x.assessment)}</td><td class="reason">${reason(x.findings)}</td><td>${x.status_code}</td><td>${num(x.first_output_ms,' ms')}</td><td>${num(x.tokens_per_second)}</td><td>${x.output_tokens??'—'}</td></tr>`).join('')+'</tbody></table>';if(bs.length)baselineContent.className='',baselineContent.innerHTML='<table><thead><tr><th>Model</th><th>Confidence</th><th>Avg Tk/s</th><th>Avg first output</th><th>Avg total</th><th>Last result</th><th>Why</th></tr></thead><tbody>'+bs.map(x=>`<tr><td>${esc(x.model)}</td><td title="${esc(x.confidenceExplanation)}">${x.successfulSamples} samples</td><td>${num(x.averageTokensPerSecond)}</td><td>${num(x.averageFirstOutputMs,' ms')}</td><td>${num(x.averageDurationMs,' ms')}</td><td>${badge(x.lastAssessment)}</td><td class="reason">${reason(x.lastFindings)}</td></tr>`).join('')+'</tbody></table>'}catch{}}
var prefs=null,wizardIndex=0;function activeWizardPages(){return [...document.querySelectorAll('.wizardPage')].filter(p=>!p.dataset.module||(p.dataset.module==='chat'&&modChat.checked)||(p.dataset.module==='baselines'&&modBaselines.checked)||(p.dataset.module==='monitor'&&modMonitor.checked)||(p.dataset.module==='evidence'&&modEvidence.checked)||(p.dataset.module==='kaspa'&&modKaspa.checked))}function showWizard(){const pages=activeWizardPages();pages.forEach(p=>p.classList.remove('active'));wizardIndex=Math.max(0,Math.min(wizardIndex,pages.length-1));pages[wizardIndex].classList.add('active');wizardBack.style.visibility=wizardIndex?'visible':'hidden';wizardNext.textContent=wizardIndex===pages.length-1?'Finish':'Next'}
async function saveConnection(){connectionResult.textContent='Testing connection…';connectionResult.className='connectionResult';const saved=await fetch('/pocisys/api/connection',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({baseUrl:backendAddress.value,provider:backendProvider.value})});if(!saved.ok){const problem=await saved.json();connectionResult.textContent=problem.error||problem.detail||'The AI address could not be saved.';connectionResult.className='connectionResult bad';return false}const response=await fetch('/pocisys/api/connection/test',{method:'POST'});const result=await response.json();connectionResult.textContent=result.explanation;connectionResult.className='connectionResult '+(result.connected?'ok':'bad');defaultModel.innerHTML='';if(result.models?.length){for(const name of result.models){const option=document.createElement('option');option.value=name;option.textContent=name;defaultModel.append(option)}}else defaultModel.innerHTML='<option value="">No models reported</option>';return result.connected}
function openSetup(){wizardIndex=0;setupModal.classList.add('open');showWizard()}async function saveSetup(){await fetch('/pocisys/api/connection',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({baseUrl:backendAddress.value,provider:backendProvider.value})});const updated={...prefs,setupComplete:true,builtInChatEnabled:modChat.checked,defaultModel:defaultModel.value||null,baselinesEnabled:modBaselines.checked,monitorCompanionEnabled:modMonitor.checked,persistentEvidenceEnabled:false,kaspaMode:modKaspa.checked?kaspaModeChoice.value:'off',monitoringSensitivity:sensitivity.value,baselineLearningRequests:Number(learningCount.value),trackContextChanges:trackContext.checked,anchorEveryEvents:Number(anchorEvents.value),anchorEveryMinutes:Number(anchorMinutes.value)};prefs=await(await fetch('/pocisys/api/preferences',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(updated)})).json();setupModal.classList.remove('open');loadStatic()}
wizardNext.onclick=()=>{const pages=activeWizardPages();if(wizardIndex===pages.length-1)saveSetup();else{wizardIndex++;showWizard()}};wizardBack.onclick=()=>{if(wizardIndex>0){wizardIndex--;showWizard()}};reopenSetup.onclick=openSetup;
async function loadStatic(){try{const [s,p,k,c]=await Promise.all([fetch('/pocisys/api/settings').then(x=>x.json()),fetch('/pocisys/api/preferences').then(x=>x.json()),fetch('/pocisys/api/kaspa/status').then(x=>x.json()),fetch('/pocisys/api/connection').then(x=>x.json())]);prefs=p;modChat.checked=p.builtInChatEnabled;modBaselines.checked=p.baselinesEnabled;modMonitor.checked=p.monitorCompanionEnabled;modEvidence.checked=p.persistentEvidenceEnabled;modKaspa.checked=p.kaspaMode!=='off';backendAddress.value=c.baseUrl;backendProvider.value=c.provider;defaultModel.innerHTML=`<option value="${esc(c.defaultModel||'')}">${esc(c.defaultModel||'Test connection to choose a model')}</option>`;sensitivity.value=p.monitoringSensitivity;learningCount.value=p.baselineLearningRequests;trackContext.checked=p.trackContextChanges;kaspaModeChoice.value=p.kaspaMode==='simulation'?'simulation':'off';anchorEvents.value=p.anchorEveryEvents;anchorMinutes.value=p.anchorEveryMinutes;settingsContent.className='';const rows={...s,builtInChat:{value:p.builtInChatEnabled?'ON':'OFF',explanation:'Provides a local reference chat at the Gateway address for personal use and end-to-end testing.'},defaultModel:{value:p.defaultModel||'Not selected',explanation:'The model selected automatically when the built-in Chat opens.'},monitoringSensitivity:{value:p.monitoringSensitivity,explanation:'Strict catches smaller changes; relaxed waits for larger differences; balanced is the normal starting point.'},baselineLearning:{value:p.baselineLearningRequests+' successful requests',explanation:'PoCiSys waits for this many successful requests before treating learned behavior as dependable.'},contextTracking:{value:p.trackContextChanges?'ON':'OFF',explanation:'Watches whether longer context accompanies slowdown and whether a session suddenly loses much of its context.'},anchorPolicy:{value:p.kaspaMode==='off'?'OFF':p.anchorEveryEvents+' events or '+p.anchorEveryMinutes+' minutes',explanation:'Closes an optional commitment batch when either limit is reached first. Live AI traffic never waits for it.'}};settingsContent.innerHTML=Object.entries(rows).map(([key,v])=>`<div class="setting"><strong>${esc(key.replace(/([A-Z])/g,' $1'))}<code>${esc(v.value??(v.enabled?'ON':'OFF'))}</code></strong><p>${esc(v.explanation)}</p></div>`).join('');kaspaMode.textContent=p.kaspaMode.toUpperCase();kaspaExplanation.textContent=p.kaspaMode==='simulation'?'Simulation can build payload plans, but no wallet is loaded and nothing is broadcast.':k.explanation;if(!p.setupComplete)openSetup()}catch{}}
testConnection.onclick=saveConnection;simulate.onclick=async()=>{anchorResult.textContent='Building commitment…';const r=await fetch('/pocisys/api/kaspa/simulate',{method:'POST'});anchorResult.textContent=JSON.stringify(await r.json(),null,2)};const initialTab=new URLSearchParams(location.search).get('tab');if(['overview','requests','baselines','settings','kaspa'].includes(initialTab))document.querySelector(`[data-tab="${initialTab}"]`)?.click();refresh();loadStatic();setInterval(refresh,1500);
</script></body></html>
""";
}
