<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>PoCiSys Gateway</AssemblyName>
    <Product>PoCiSys Gateway</Product>
    <Company>PoCiSys</Company>
    <Version>0.3.1</Version>
    <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
    <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
  </PropertyGroup>
</Project>
